spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true